export const GESTURE_CONSTANTS = {
  DEFAULT_ROTATION_SPEED: 0.005,
  DEFAULT_SENSITIVITY: 1,
  DEFAULT_Z_MULTIPLIER: 100,
  INITIAL_ROTATION: 0,
  INITIAL_POSITION: { x: 0, y: 0, z: 0 },
  INITIAL_ZOOM_SCALE: 1,
};
