"""Init

Revision ID: e21c1e12ed8e
Revises: 3d35e0512814
Create Date: 2026-01-25 02:12:46.638252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e21c1e12ed8e'
down_revision: Union[str, Sequence[str], None] = '3d35e0512814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithmsolution', sa.Column('case_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'algorithmsolution', 'algorithmcase', ['case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'algorithmsolution', type_='foreignkey')
    op.drop_column('algorithmsolution', 'case_id')
    # ### end Alembic commands ###
